=== antoniotejedalp-jpg/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dirrecion (nombrecompleto, correo, telefono, cumple)>
<!ELEMENT nombrecompleto (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== antoniotejedalp-jpg/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dirrecion SYSTEM "xml-00.dtd">
<dirrecion>
    <nombrecompleto>
        <nombre>Antonio</nombre>
        <apellidos>Tejeda</apellidos>
    </nombrecompleto>
    <correo>antonio@gmail.com</correo>
    <telefono>1234567890</telefono>
    <cumple>
        <dia>1</dia>
        <mes>1</mes>
        <anio>1</anio>
    </cumple>
</dirrecion>
